#
# kintara: malkier xmpp server
# etc/config.yml: configuration information
#
# Copyright (c) 2003-2009 Eric Will <rakaur@malkier.net>
#
# encoding: utf-8

# This file is written in YAML. I decided to go with it over the
# complex C-style configuration in synapse for a few reasons:
#
#   1) It's very simple.
#   2) Ruby can parse it with one method call rather than an entire library.
#   3) It's very Ruby-ish instead of C-ish, and that's what I'm going for.
#

# Define domains this daemon will service. Sort of like virtual hosts.
domains: malkier.net, optera.org

##
# Define listen ports. Entries are in the form of host:port.
#
# c2s = client-to-server ports. You must define at least one.
# s2s = server-to-server ports. Omitting disables server federation.
#
# certificate = The certificate used for STARTTLS.
# If you're like most people you'll have to generate
# your own, self-signed certificate rather than pay
# an ungodly sum of money to some company. In order to
# do this you need to issue these commands:
#                                          
# To generate a private key to self-sign:
#     openssl genrsa -out cert.key -rand /dev/urandom 1024
#
# To generate a self-signed certificate:
#     openssl req -x509 -new -key cert.key -out cert.pem
#
# Move the resulting "cert.pem" file to this location.
#
# If you have otherwise acquired a certificate and a separate
# private key, you need to combine them into one file and put
# that here.
#
listen:
    c2s: *:5222
    s2s: *:5269

    certificate: etc/cert.pem

##
# Define who may connect to this service. The default allows everyone.
#
# hosts   = list of hosts that are allowed to connect.
# matches = list of valid Ruby regular expressions. Omit /slashes/.
#
authorize:
    matches: (.*) # <- Everyone.
#   hosts:   192.168.0.1, 127.0.0.1
#   matches: 192\.168\.1\.(\d+)

# This is here to make sure you read the config.
#die: true

##
# Define who may NOT connect to this service.
#
# hosts   = list of hosts that are allowed to connect.
# matches = list of valid Ruby regular expressions. Omit /slashes/.
deny:
#   hosts:   127.0.0.1, 192.168.0.1
#   matches: 192\.168\.2\.(\d+)

##
# Define users that are allowed to perform administrative operations.
#
# Available privileges:
#
#   announce = May send server-wide messages.
operators:
    rakaur: announce
